### PR TITLE
Click to copy section

### PR DESCRIPTION
**Pull request by marcus-ong-qy**
Reusable component with a click-to-copy text and an optional title

(when clicking)
Screenshot 2022-01-06 223340

(not clicking)
Screenshot 2022-01-06 223423

### CODE REVIEW

**Comment by marcus-ong-qy** [comment]
[click to copy section](https://trello.com/c/pIRxzG6k/11-click-to-copy-section)

**Review by rldefa — APPROVED** [review]
LGTM, will appreciate a screenshot in the description in the future. Nice and clean and versatile component well done : )

**Comment by rldefa** [comment]
Actually would some animation on click be good? right now I can't tell visually if clicking has done anything.

**Comment by marcus-ong-qy** [comment]
> Actually would some animation on click be good? right now I can't tell visually if clicking has done anything.
hmm ok maybe I shall try to experiment with that

**Comment by marcus-ong-qy** [comment]
> Actually would some animation on click be good? right now I can't tell visually if clicking has done anything.

ok added screenshots and click highlight

**Pull request merged**
