### PR TITLE
Add error handling to InputField

### PR DESCRIPTION
**Pull request by marcus-ong-qy**
Features:
- Tooltip will appear for 2s if input field is invalid, upon clicking on form 'submit' button
- Supports custom tooltip error message, validation regex and browser error message (currently only 'name' is available)
- Input border turns red onClick and onInput when entry is invalid
- Browser tooltip error message (google chrome shown on pic) cannot be disabled, hence I used it to display custom validation message

Screenshot 2022-01-23 095114

### CODE REVIEW

**Comment by marcus-ong-qy** [comment]
[Add error handling to input field](https://trello.com/c/F1GJHODc/13-add-error-handling-to-input-field)

**Comment by kiyonggg** [comment]
can you provide a simple example to display the tooltip? i can view the browser tooltip error message but i cant seem to toggle the tooltip

**Comment by marcus-ong-qy** [comment]
> can you provide a simple example to display the tooltip? i can view the browser tooltip error message but i cant seem to toggle the tooltip.
> 
> otherwise, points 2, 3 and 4 are okay

For our tooltip, the input field needs to be in a html form, and is triggered by the form's submit button

**Review by kiyonggg — APPROVED** [review]
lgtm!

**Pull request merged**
